### PR TITLE
Documenting of code, and minor code changes

### PR DESCRIPTION
**Pull request by crypdick**
I read your code line-by-line and added documentation. Hopefully I interpreted everything correctly!

I made some minor edits to play_one_episode. I commented out some unused definitions, and ran the files through a PEP8 linter to clean up the style. I am pretty confident everything should work, but I can't test whether I broke anything without training data.

Finally, I deleted the Atari code at the end of expreplay.py

### CODE REVIEW

**Comment by amiralansary** [comment]
I just added some test data and a pre-trained model. I hope this ease testing any new changes. Thanks!

**Comment by crypdick** [comment]
Ok, I carefully merged your changes and tested that everything works with your sample data. You can review my changes side-by-side [here](https://github.com/amiralansary/tensorpack-medical/compare/master...crypdick:master). The most aggressive change is deleting 2 unused Class definitions.

**Comment by crypdick** [comment]
e236882 fixes an error due to a `train=False` kwarg being renamed to `task=False` in a recent commit

**Comment by amiralansary** [comment]
I checked the changes and did few test, it seems to be working fine too. The changes are merged now. Thank you for the contribution here! :)

**Pull request merged**
